### ISSUE TITLE
Pipeline from pointcloud file to input?

### ISSUE THREAD

**Issue by BenjiDayan** [laughtervv/SGPN#10]
Hi @laughtervv ,

Thanks for sharing your code, 
I've been trying to figure out how to preprocess new room pointcloud data to run on your pretrained stanford dataset model, without much success. 

Do you have any programs or pipelines for this? How did you convert the stanford point cloud txt file data into the 9 vector format? Along with the conversion into blocks?
There are some functions in utils.pc_util and utils.plyfile for loading ply files, but these also seem insufficient?

Thanks again.

**Comment by BenjiDayan** [comment]
I guess my question is a continuation of Issue #3 , of how did you prepare the h5 files?
Thanks ~

**Comment by laughtervv** [comment]
I'll update the repo with data preparation soon.
