### ISSUE TITLE
Group Merging Very Slow. Also high RAM usage?

### ISSUE THREAD

**Issue by BenjiDayan** [laughtervv/SGPN#11]
Hi @laughtervv ,

I've been trying to run your pretrained S3DIS model on point clouds from the matterport dataset. However I've found that group merging is very slow, for instance on a room divided into about 80 blocks, around 10000 points per block, group merging takes 5 mins + per block (if running on one cpu). Maybe I'm doing something wrong, did you also encounter this?

A separate problem is that to load one room into memory can take 30+ GB RAM, though I guess you could store and load on demand by block the model's output?

Sorry for all the questions, but also I've found group instance segmentation results to be a bit shoddy, perhaps it's something to do with the mingroupsize.txt and the pergroup_thres.txt and other thresholds? How did you get these values? I'm currently using the ones you posted on Issue #8. 

Thanks for any help.

**Comment by laughtervv** [comment]
Group merging might be slow on large point cloud. 
I preloaded the data into ram before training, so it may take time. You may load data in an online fashion and use cache (refer to [here](https://github.com/charlesq34/pointnet-autoencoder/blob/master/part_dataset.py)). 
valid.py is used to generate mingroupsize.txt and the pergroup_thres.txt.
