### ISSUE TITLE
Where are the associate files for the checkpoint?

### ISSUE THREAD

**Issue by avfkg** [laughtervv/SGPN#12]
Hi,
First of all thanks for sharing your nice work!
I was trying to run test.py on the example data provided [here](https://drive.google.com/file/d/1-e7YCfrLB4zqbFyWfQGe8sm_QFNrr59K/view?usp=sharing) which tries to use some Restore Directory: 

> checkpoint/stanford_ins_seg_groupmask11_fromgroup_recipweight_nopow2_lr4

It looks there to find the files:

> pergroup_thres.txt

> mingroupsize.txt

Now I was wondering if these files could also be provided, or alternatively what they contain.

Any help is much appreciated!

**Comment by BenjiDayan** [comment]
@avfkg ,
Hi I think you produce those files from running valid.py. Somebody also posted their versions in some previous issue

**Comment by avfkg** [comment]
@Ziggareto Thanks! You're right!
