### ISSUE TITLE
I wantna to know how to perpare the .h5 file?

### ISSUE THREAD

**Issue by chuliuT** [laughtervv/SGPN#13]
Hi vv:
          i looking  a solution to make the .h5 file,for training my own dataset,but i dont't know how to do, Could you give me a help?

**Comment by BenjiDayan** [comment]
@EthonDeep , check out https://github.com/qianguih/RSNet, it's a very similar task / setup, I believe the tools for data preparation there are shared for SGPN since they're coauthors.

**Comment by EthonDeep** [comment]
@@EthonDeep，thanks！

**Comment by chuliuT** [comment]
@Ziggareto ，thanks！

**Comment by justbin1123** [comment]
@Aivision-tang29  Hi，Have you completed the data(h5) preparation work? I have referenced the work of https://github.com/qianguih/RSNet. But the data i got doesnt  exactly match the SGPN. Did u change the  data preparation code in RSNet?  
Could you give me a help?
