### ISSUE TITLE
How to joint pre-trained pointnet model

### ISSUE THREAD

**Issue by MaxMece** [laughtervv/SGPN#17]
Hello @laughtervv :
       i've trained SGPN on our own dataset.but i don't know how to joint pre-trained pointnet model, when i directly put the pointnet model to restore_model path, some error occurred, like key Fsem/bias not found in checkpoint and so on. but in original pointnet model, Fsem variable does not exist. or poinetnet doesn't need to pre-train?
       could you please help me about this problem.
       Thanks.

**Comment by lhiceu** [comment]
Hi @MaxMece 
I have the same confusion. D you have the solution?
