### ISSUE TITLE
error when running valid.py

### ISSUE THREAD

**Issue by amiltonwong** [laughtervv/SGPN#2]
Hi, @laughtervv ,

I got the following error when I run `valid.py`

```
(py2.7_tf1.4) root@milton-ThinkCentre-M93p:/data/code6/SGPN# python valid.py 
Traceback (most recent call last):
  File "valid.py", line 6, in <module>
    from utils.test_utils import *
  File "/data/code6/SGPN/utils/test_utils.py", line 310, in <module>
    magma_cmap = mpl.cm.get_cmap('magma')
AttributeError: 'module' object has no attribute 'cm'

```
I can run `python train.py` successfully before running `valid.py`.
Could you suggest me how to fix it?

THX!

**Comment by mr-scrawley** [comment]
I encountered the same problem and was able to fix it with an additional, explicit import:
`import matplotlib.cm`
