### ISSUE TITLE
KeyError: "Unable to open object (object 'pid' doesn't exist)"

### ISSUE THREAD

**Issue by WangY69** [laughtervv/SGPN#36]
Hello， @laughtervv 
I have downloaded the   indoor3d_sem_seg_hdf5_data，but I have a error：

Fail to load modelfile: checkpoint/stanford_ins_seg/trained_models/
Traceback (most recent call last):
  File "train.py", line 277, in <module>
    train()
  File "train.py", line 177, in train
    cur_data, cur_group, _, cur_seg = provider.loadDataFile_with_groupseglabel_stanfordindoor(cur_train_filename)
  File "/data/zyu/wangyu/wangy/SGPN-master/provider.py", line 207, in loadDataFile_with_groupseglabel_stanfordindoor
    group = f['pid'][:].astype(np.int32)#NxG
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zyu/anaconda3/lib/python3.6/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
**KeyError: "Unable to open object (object 'pid' doesn't exist)"**

I think it’s related to the train_hdf5_file_list.txt, but I don't how to  write train_hdf5_file_list.txt and  didn't get the steps in details. Can you give some suggestion?
Thanks for your response.

**Comment by wffancy** [comment]
@WangY69 Hi, I had met the same problem as yours. coud you please share the solution out?

**Comment by WangY69** [comment]
> @WangY69 Hi, I had met the same problem as yours. coud you please share the solution out?

You must write each entry in train_hdf5_file_list.txt correctly, such as data/indoor3d_ins_seg_hdf5/Area_1_conferenceRoom_1.h5. Make sure to add the file extension .h5 to each entry so that h5py can load the data properly.

**Comment by wffancy** [comment]
> > @WangY69 Hi, I had met the same problem as yours. coud you please share the solution out?
> 
> You must write each entry in train_hdf5_file_list.txt correctly, such as data/indoor3d_ins_seg_hdf5/Area_1_conferenceRoom_1.h5. Make sure to add the file extension .h5 to each entry so that h5py can load the data properly.

thanks for your prompt reply~ However, from the directory you give I suppose I have used the wrong training data... It seems that the author didn't give the detailed insturctions about the data preparation. And I finally use the data from the repository [PointNet](https://github.com/charlesq34/pointnet/tree/master/sem_seg) so my directory would look like data/indoor3d_sem_seg_hdf5_data/ply_data_all_0.h5 . I have struggled about the data preparation problem all day, so I wonder could you please share the link to download the instance segmentation data or give me some other instructions. Thanks.

**Comment by WangY69** [comment]
> > > @ WangY69嗨，我遇到了与您相同的问题。可以请您分享解决方案吗？
> > 
> > 
> > 您必须正确地将每个条目写在train_hdf5_file_list.txt中，例如data / indoor3d_ins_seg_hdf5 / Area_1_conferenceRoom_1.h5。确保将文件扩展名.h5添加到每个条目，以便h5py可以正确加载数据。
> 
> 感谢您的迅速答复〜但是，我想从您给的目录中使用了错误的训练数据...看来作者没有提供有关数据准备的详细说明。最后，我使用了[PointNet](https://github.com/charlesq34/pointnet/tree/master/sem_seg)仓库中的数据，因此我的目录看起来像data / indoor3d_sem_seg_hdf5_data / ply_data_all_0.h5。我整天都在为数据准备问题而苦苦挣扎，所以我想知道您能否分享链接以下载实例细分数据或给我一些其他说明。谢谢。
https://drive.google.com/file/d/1UjcXB2wMlLt5qwYPk5iSAnlhttl1AO9u/view?ts=5aecefd1。

**Comment by wffancy** [comment]
> > > > @ WangY69嗨，我遇到了与您相同的问题。可以请您分享解决方案吗？
> > > 
> > > 
> > > 您必须正确地将每个条目写在train_hdf5_file_list.txt中，例如data / indoor3d_ins_seg_hdf5 / Area_1_conferenceRoom_1.h5。确保将文件扩展名.h5添加到每个条目，以便h5py可以正确加载数据。
> > 
> > 
> > 感谢您的迅速答复〜但是，我想从您给的目录中使用了错误的训练数据...看来作者没有提供有关数据准备的详细说明。最后，我使用了[PointNet](https://github.com/charlesq34/pointnet/tree/master/sem_seg)仓库中的数据，因此我的目录看起来像data / indoor3d_sem_seg_hdf5_data / ply_data_all_0.h5。我整天都在为数据准备问题而苦苦挣扎，所以我想知道您能否分享链接以下载实例细分数据或给我一些其他说明。谢谢。
> > [https://drive.google.com/file/d/1UjcXB2wMlLt5qwYPk5iSAnlhttl1AO9u/view?ts=5aecefd1。](https://drive.google.com/file/d/1UjcXB2wMlLt5qwYPk5iSAnlhttl1AO9u/view?ts=5aecefd1%E3%80%82)

我找到这个了，但是链接好像失效了，没有下载的选项。。

**Comment by WangY69** [comment]
> > > > > @ WangY69嗨，我遇到了与您相同的问题。可以请您分享解决方案吗？
> > > > 
> > > > 
> > > > 您必须正确地将每个条目写在train_hdf5_file_list.txt中，例如data / indoor3d_ins_seg_hdf5 / Area_1_conferenceRoom_1.h5。确保将文件扩展名.h5添加到每个条目，以便h5py可以正确加载数据。
> > > 
> > > 
> > > 感谢您的迅速答复〜但是，我想从您给的目录中使用了错误的训练数据...看来作者没有提供有关数据准备的详细说明。最后，我使用了[PointNet](https://github.com/charlesq34/pointnet/tree/master/sem_seg)仓库中的数据，因此我的目录看起来像data / indoor3d_sem_seg_hdf5_data / ply_data_all_0.h5。我整天都在为数据准备问题而苦苦挣扎，所以我想知道您能否分享链接以下载实例细分数据或给我一些其他说明。谢谢。
> > > [https://drive.google.com/file/d/1UjcXB2wMlLt5qwYPk5iSAnlhttl1AO9u/view?ts=5aecefd1。](https://drive.google.com/file/d/1UjcXB2wMlLt5qwYPk5iSAnlhttl1AO9u/view?ts=5aecefd1%E3%80%82)
> 
> 我找到这个了，但是链接好像失效了，没有下载的选项。。

https://drive.google.com/drive/folders/1s1cFfb8cInM-SNHQoTGxN9BIyNpNQK6x

**Comment by wffancy** [comment]
> > > > > > @ WangY69嗨，我遇到了与您相同的问题。可以请您分享解决方案吗？
> > > > > 
> > > > > 
> > > > > 您必须正确地将每个条目写在train_hdf5_file_list.txt中，例如data / indoor3d_ins_seg_hdf5 / Area_1_conferenceRoom_1.h5。确保将文件扩展名.h5添加到每个条目，以便h5py可以正确加载数据。
> > > > 
> > > > 
> > > > 感谢您的迅速答复〜但是，我想从您给的目录中使用了错误的训练数据...看来作者没有提供有关数据准备的详细说明。最后，我使用了[PointNet](https://github.com/charlesq34/pointnet/tree/master/sem_seg)仓库中的数据，因此我的目录看起来像data / indoor3d_sem_seg_hdf5_data / ply_data_all_0.h5。我整天都在为数据准备问题而苦苦挣扎，所以我想知道您能否分享链接以下载实例细分数据或给我一些其他说明。谢谢。
> > > > [https://drive.google.com/file/d/1UjcXB2wMlLt5qwYPk5iSAnlhttl1AO9u/view?ts=5aecefd1。](https://drive.google.com/file/d/1UjcXB2wMlLt5qwYPk5iSAnlhttl1AO9u/view?ts=5aecefd1%E3%80%82)
> > 
> > 
> > 我找到这个了，但是链接好像失效了，没有下载的选项。。
> 
> https://drive.google.com/drive/folders/1s1cFfb8cInM-SNHQoTGxN9BIyNpNQK6x

十分感谢！

**Comment by wffancy** [comment]
@WangY69  很抱歉又打扰了，我把数据集下载下来放在对应的文件夹内，且填好了train_hdf5_file_list.txt文件，但是遇到了 #33 问题，不知道您是否知道如何解决，我用 h5py.File 读取了h5文件中存在有的键值，发现确实没有'data'，不知哪里还有错误，望赐教
