### ISSUE TITLE
How to convert instance results to 3D bounding boxes of Object detection?

### ISSUE THREAD

**Issue by shuluoshu** [laughtervv/SGPN#4]
Hi, @laughtervv , @Rotch ,
I wonder if you could offer the code for converting instance segmentation results into **3D bounding boxes** of object detection, since I don't know how to compute the orientation of the bounding box.
 Thanks a lot!

**Comment by CrazySnailer** [comment]
Drawing 3D bounding boxes need priori knowledge, Like Frustum Pointnet, the orientation of the bounding box need to be regression by the priori knowledge. Look forward to discuss with you.

**Comment by laughtervv** [comment]
In our detection experiment, we didn't consider the box orientation. Both ground truth and the predicted bounding boxes are computed by the min-max xyz value of point cloud instances.

**Comment by CrazySnailer** [comment]
@laughtervv Thanks.
